In [8]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv(r"data\raw\preprocessed_data.csv")
df

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,0,0.000000,0,224,2017,10,2,3,0.0,0.0,0.0,65.000000,0,1
1,2,0,2,3,3,0.000000,0,5,2018,11,6,4,0.0,0.0,0.0,106.680000,1,1
2,1,0,2,1,0,0.000000,0,1,2018,2,28,4,0.0,0.0,0.0,60.000000,0,0
3,2,0,0,2,0,0.000000,0,211,2018,5,20,4,0.0,0.0,0.0,100.000000,0,0
4,2,0,1,1,3,0.000000,0,48,2018,4,11,4,0.0,0.0,0.0,94.500000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48775,2,0,0,2,1,0.000000,0,265,2018,6,24,4,0.0,0.0,0.0,115.000000,1,0
48776,1,0,2,4,0,0.000000,0,68,2017,6,22,3,0.0,0.0,0.0,77.394578,0,0
48777,2,0,0,2,0,0.322461,0,219,2018,9,13,4,0.0,0.0,0.0,140.286918,1,0
48778,2,0,0,5,1,0.000000,0,230,2018,9,6,3,0.0,0.0,0.0,137.000000,0,0
48779,1,0,0,2,0,0.000000,0,17,2017,5,28,3,0.0,0.0,0.0,79.581038,0,0

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
X = df.drop(columns="booking_status")
y = df["booking_status"]

In [12]:
model = RandomForestClassifier(random_state=42)
model.fit(X,y)

RandomForestClassifier(random_state=42)

In [15]:
feature_importance = model.feature_importances_

In [ ]:
feature_importance_df = pd.DataFrame({
    'feature' : X.columns,
    'importance' :feature_importance
})

In [20]:
top_feature_importance_df=feature_importance_df.sort_values(by="importance", ascending=False)

In [23]:
top_feature_importance_df

                                 feature  importance
7                              lead_time    0.306601
15                    avg_price_per_room    0.146218
16                no_of_special_requests    0.139844
9                          arrival_month    0.086525
10                          arrival_date    0.082898
11                   market_segment_type    0.057676
3                      no_of_week_nights    0.045198
2                   no_of_weekend_nights    0.032302
8                           arrival_year    0.023577
0                           no_of_adults    0.021759
4                      type_of_meal_plan    0.019846
6                     room_type_reserved    0.015857
5             required_car_parking_space    0.008312
1                         no_of_children    0.005520
12                        repeated_guest    0.005027
14  no_of_previous_bookings_not_canceled    0.002277
13          no_of_previous_cancellations    0.000565

In [26]:
top_10_features = top_feature_importance_df["feature"].head(10).values

top_10_df = df[top_10_features.tolist() + ["booking_status"]]

In [27]:
top_10_df

,lead_time,avg_price_per_room,no_of_special_requests,arrival_month,arrival_date,market_segment_type,no_of_week_nights,no_of_weekend_nights,arrival_year,no_of_adults,booking_status
0,224,65.000000,0,10,2,3,2,1,2017,2,1
1,5,106.680000,1,11,6,4,3,2,2018,2,1
2,1,60.000000,0,2,28,4,1,2,2018,1,0
3,211,100.000000,0,5,20,4,2,0,2018,2,0
4,48,94.500000,0,4,11,4,1,1,2018,2,0
...,...,...,...,...,...,...,...,...,...,...,...
48775,265,115.000000,1,6,24,4,2,0,2018,2,0
48776,68,77.394578,0,6,22,3,4,2,2017,1,0
48777,219,140.286918,1,9,13,4,2,0,2018,2,0
48778,230,137.000000,0,9,6,3,5,0,2018,2,0
48779,17,79.581038,0,5,28,3,2,0,2017,1,0

In [ ]:
if os.path.exists(r"data\raw\top_features.csv"):
    print("File already exists")
else:
    top_10_df.to_csv(r"data\raw\top_features.csv", index= False)