In [18]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn. linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [20]:
df = pd.read_csv(r"data\raw\top_features.csv")

In [21]:
df

,lead_time,avg_price_per_room,no_of_special_requests,arrival_month,arrival_date,market_segment_type,no_of_week_nights,no_of_weekend_nights,arrival_year,no_of_adults,booking_status
0,224,65.000000,0,10,2,3,2,1,2017,2,1
1,5,106.680000,1,11,6,4,3,2,2018,2,1
2,1,60.000000,0,2,28,4,1,2,2018,1,0
3,211,100.000000,0,5,20,4,2,0,2018,2,0
4,48,94.500000,0,4,11,4,1,1,2018,2,0
...,...,...,...,...,...,...,...,...,...,...,...
48775,265,115.000000,1,6,24,4,2,0,2018,2,0
48776,68,77.394578,0,6,22,3,4,2,2017,1,0
48777,219,140.286918,1,9,13,4,2,0,2018,2,0
48778,230,137.000000,0,9,6,3,5,0,2018,2,0
48779,17,79.581038,0,5,28,3,2,0,2017,1,0

In [22]:
X = df.drop(columns='booking_status')
y = df['booking_status']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
X_train

,lead_time,avg_price_per_room,no_of_special_requests,arrival_month,arrival_date,market_segment_type,no_of_week_nights,no_of_weekend_nights,arrival_year,no_of_adults
19174,113,100.000000,0,5,31,2,3,0,2018,1
24889,87,135.150000,2,5,15,4,2,2,2018,2
43330,103,115.000000,0,4,19,3,2,0,2018,1
48201,31,78.379201,0,2,7,4,0,1,2018,2
3287,38,83.900000,1,3,5,4,1,2,2018,2
...,...,...,...,...,...,...,...,...,...,...
11284,5,110.000000,1,5,24,2,2,0,2018,2
44732,69,76.292486,1,6,12,4,0,1,2017,2
38158,198,90.900000,0,10,18,4,3,0,2018,1
860,213,130.000000,0,6,7,4,3,0,2018,2
15795,14,167.200000,0,9,15,4,2,0,2018,2

In [25]:
y_train

19174    0
24889    1
43330    0
48201    0
3287     1
        ..
11284    1
44732    0
38158    0
860      0
15795    1
Name: booking_status, Length: 39024, dtype: int64

In [26]:
classifiers = {
    "Random Forest" : RandomForestClassifier(random_state=42),
    "Gradientboost" : GradientBoostingClassifier(random_state=42),
    "Adaboost" : AdaBoostClassifier(random_state=42),
    "Logistic Regression" : LogisticRegression(random_state=42),
    "Decision Tree" : DecisionTreeClassifier(random_state=42),
    "Support Vector Classifier" : SVC(random_state=42),
    "Gaussian NB" : GaussianNB(),
    "KNN Classifier" : KNeighborsClassifier(),
    "XGboost" : XGBClassifier(),
    "LightGBM" : LGBMClassifier(random_state=42),
}

In [27]:
metrics = {
    "Model" : [],
    "Accuracy" : [],
    "Precision" : [],
    "Recall" : [],
    "F1 score" : [],
}

In [28]:
for model_name, classifier in classifiers.items():
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    metrics["Model"].append(model_name)
    metrics["Accuracy"].append(accuracy)
    metrics["Precision"].append(precision)
    metrics["Recall"].append(recall)
    metrics["F1 score"].append(f1)

c:\Users\LaukikS\anaconda3\envs\ml-dl-env\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[LightGBM] [Info] Number of positive: 19518, number of negative: 19506
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005092 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 584
[LightGBM] [Info] Number of data points in the train set: 39024, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500154 -> initscore=0.000615
[LightGBM] [Info] Start training from score 0.000615

In [29]:
metrics_df = pd.DataFrame(metrics)

In [31]:
metrics_df

                       Model  Accuracy  Precision    Recall  F1 score
0              Random Forest  0.918102   0.910171  0.927545  0.918776
1              Gradientboost  0.835691   0.830135  0.843596  0.836812
2                   Adaboost  0.776855   0.763132  0.802135  0.782148
3        Logistic Regression  0.788643   0.786384  0.791872  0.789118
4              Decision Tree  0.885199   0.892962  0.875000  0.883890
5  Support Vector Classifier  0.686859   0.654376  0.790435  0.715999
6                Gaussian NB  0.755740   0.772260  0.724548  0.747644
7             KNN Classifier  0.830361   0.856889  0.792693  0.823542
8                    XGboost  0.896064   0.885800  0.909072  0.897285
9                   LightGBM  0.884174   0.867728  0.906199  0.886546